org: mikesol
app: klank-dev

service: klank-dev
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  memorySize: 4096
  iamRoleStatements:
    - Effect: "Allow"
      Action: "s3:*"
      Resource: "arn:aws:s3:::klank-share"
    - Effect: "Allow"
      Action: "s3:*"
      Resource: "arn:aws:s3:::klank-share/*"

functions:
  compile-klank:
    timeout: 29
    handler: compile.handler
    events:
      - http:
          method: post
          path: compile
          cors: true
    environment:
      MIXPANEL_TOKEN: "88b2855ebbc656315bace43f141d7f3f"
  upload-file:
    timeout: 29
    handler: ufile.handler
    events:
      - http:
          method: post
          path: u
          cors: true
    environment:
      MIXPANEL_TOKEN: "88b2855ebbc656315bace43f141d7f3f"
  upload-klank:
    timeout: 29
    handler: uklank.handler
    events:
      - http:
          method: post
          path: uk
          cors: true
    environment:
      MIXPANEL_TOKEN: "88b2855ebbc656315bace43f141d7f3f"
