module Klank.Studio.SilentNight.AudioFiles where

import Data.Tuple (Tuple(..))

audioFiles :: Array (Tuple String String)
audioFiles =
  [ Tuple "metronome-wb" "https://freesound.org/data/previews/53/53403_400592-lq.mp3"
  , Tuple "hb1" "https://klank-share.s3-eu-west-1.amazonaws.com/silent-night/hb1.ogg"
  , Tuple "hb2" "https://klank-share.s3-eu-west-1.amazonaws.com/silent-night/hb2.ogg"
  , Tuple "IntroLoopA" "https://klank-share.s3-eu-west-1.amazonaws.com/silent-night/introC.mp3"
  , Tuple "IntroLoopB" "https://klank-share.s3-eu-west-1.amazonaws.com/silent-night/introD.mp3"
  , Tuple "IntroLoopC" "https://klank-share.s3-eu-west-1.amazonaws.com/silent-night/introA.mp3"
  , Tuple "IntroLoopD" "https://klank-share.s3-eu-west-1.amazonaws.com/silent-night/introB.mp3"
  , Tuple "IntroLoopE" "https://klank-share.s3-eu-west-1.amazonaws.com/silent-night/introE.mp3"
  , Tuple "v1t1" "https://klank-share.s3-eu-west-1.amazonaws.com/silent-night/v1t1.mp3"
  , Tuple "v1t2" "https://klank-share.s3-eu-west-1.amazonaws.com/silent-night/v1t2.mp3"
  , Tuple "v1t3" "https://klank-share.s3-eu-west-1.amazonaws.com/silent-night/v1t3.mp3"
  , Tuple "v1t4" "https://klank-share.s3-eu-west-1.amazonaws.com/silent-night/v1t4.mp3"
  , Tuple "v1t5" "https://klank-share.s3-eu-west-1.amazonaws.com/silent-night/v1t5.mp3"
  , Tuple "v1t2" "https://klank-share.s3-eu-west-1.amazonaws.com/silent-night/v1t6.mp3" -- v1t7 has bug, needs to fix
  , Tuple "v1t7" "https://klank-share.s3-eu-west-1.amazonaws.com/silent-night/v1t7.mp3"
  , Tuple "v1t8" "https://klank-share.s3-eu-west-1.amazonaws.com/silent-night/v1t8.mp3"
  , Tuple "v2t1" "https://klank-share.s3-eu-west-1.amazonaws.com/silent-night/v2t1.mp3"
  , Tuple "v2t2" "https://klank-share.s3-eu-west-1.amazonaws.com/silent-night/v2t2.mp3"
  , Tuple "v2t3" "https://klank-share.s3-eu-west-1.amazonaws.com/silent-night/v2t3.mp3"
  , Tuple "v2t4" "https://klank-share.s3-eu-west-1.amazonaws.com/silent-night/v2t4.mp3"
  , Tuple "v2t5" "https://klank-share.s3-eu-west-1.amazonaws.com/silent-night/v2t5.mp3"
  , Tuple "v2t6" "https://klank-share.s3-eu-west-1.amazonaws.com/silent-night/v2t6.mp3"
  , Tuple "v2t7" "https://klank-share.s3-eu-west-1.amazonaws.com/silent-night/v2t7.mp3"
  , Tuple "v2t8" "https://klank-share.s3-eu-west-1.amazonaws.com/silent-night/v2t8.mp3"
  , Tuple "v3t1" "https://klank-share.s3-eu-west-1.amazonaws.com/silent-night/v3t1.mp3"
  , Tuple "v3t2" "https://klank-share.s3-eu-west-1.amazonaws.com/silent-night/replaceSomething.mp3" -- "https://klank-share.s3-eu-west-1.amazonaws.com/silent-night/v3t2-t1.ogg"
  , Tuple "v3t3" "https://klank-share.s3-eu-west-1.amazonaws.com/silent-night/v3t3.mp3"
  , Tuple "v3t4" "https://klank-share.s3-eu-west-1.amazonaws.com/silent-night/v3t4.mp3"
  , Tuple "v3t5" "https://klank-share.s3-eu-west-1.amazonaws.com/silent-night/v3t5.mp3"
  , Tuple "v3t6" "https://klank-share.s3-eu-west-1.amazonaws.com/silent-night/v3t6.mp3"
  , Tuple "v3t7" "https://klank-share.s3-eu-west-1.amazonaws.com/silent-night/v3t7.mp3"
  , Tuple "v3t8" "https://klank-share.s3-eu-west-1.amazonaws.com/silent-night/v3t8.mp3"
  , Tuple "justGuitar" "https://klank-share.s3-eu-west-1.amazonaws.com/silent-night/justGuitar.ogg"
  , Tuple "choiceBell" "https://freesound.org/data/previews/411/411089_5121236-hq.mp3"
  , Tuple "motion" "https://klank-share.s3-eu-west-1.amazonaws.com/silent-night/motion-no-howl-2.ogg"
  , Tuple "snow" "https://klank-share.s3-eu-west-1.amazonaws.com/silent-night/snow.mp3"
  , Tuple "triangle" "https://freesound.org/data/previews/199/199822_3485902-hq.mp3"
  , Tuple "square1" "https://klank-share.s3-eu-west-1.amazonaws.com/in-a-sentimental-mood/Samples/Windchime/Tiny-Metal---Jangle-4.r.ogg"
  , Tuple "square2" "https://klank-share.s3-eu-west-1.amazonaws.com/in-a-sentimental-mood/Samples/Windchime/Medium-Metal---Jangle-6.r.ogg"
  , Tuple "square3" "https://klank-share.s3-eu-west-1.amazonaws.com/in-a-sentimental-mood/Samples/Windchime/Tiny-Metal---Jangle-7.r.ogg"
  , Tuple "square4" "https://klank-share.s3-eu-west-1.amazonaws.com/in-a-sentimental-mood/Samples/Windchime/Large-Metal---Jangle-3.r.ogg"
  , Tuple "square5" "https://klank-share.s3-eu-west-1.amazonaws.com/in-a-sentimental-mood/Samples/Windchime/Smol-Metal---Jangle-7.r.ogg"
  , Tuple "gearBowl" "https://klank-share.s3-eu-west-1.amazonaws.com/in-a-sentimental-mood/Samples/SingingBowls/Small---Perform-1.r.ogg"
  , Tuple "large-birds" "https://freesound.org/data/previews/387/387978_6221013-hq.mp3"
  , Tuple "large-market" "https://klank-share.s3-eu-west-1.amazonaws.com/silent-night/129677_2355772-hq.mp3"
  , Tuple "large-chimes" "https://freesound.org/data/previews/136/136299_1645319-hq.mp3"
  , Tuple "large-synth" "https://freesound.org/data/previews/353/353501_5121236-hq.mp3" -- "Ambience, Wind Chimes, A.wav" by InspectorJ (www.jshaw.co.uk) of Freesound.org
  , Tuple "large-santa" "https://klank-share.s3-eu-west-1.amazonaws.com/silent-night/santa.mp3"
  , Tuple "rise" "https://freesound.org/data/previews/110/110158_649468-hq.mp3"
  , Tuple "sb43" "https://klank-share.s3-eu-west-1.amazonaws.com/silent-night/Bells/sb43.ogg"
  , Tuple "sb38" "https://klank-share.s3-eu-west-1.amazonaws.com/silent-night/Bells/sb38.ogg"
  , Tuple "sb33" "https://klank-share.s3-eu-west-1.amazonaws.com/silent-night/Bells/sb33.ogg"
  ]
